version: '3.8'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    container_name: oracle-db
    platform: linux/amd64
    environment:
      ORACLE_PWD: oracle
    ports:
      - "1521:1521"

  my-app:
    build: src
    container_name: my-transfer-money-app
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: oracle
    ports:
      - "8080:8080"